version: "2.1"
services:
  db:
    image: mysql:5.6
    container_name: edx_enterprise_subsidy.db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - devstack_default
    volumes:
      - edx_enterprise_subsidy_mysql:/var/lib/mysql

  memcache:
    image: memcached:1.4.24
    container_name: edx_enterprise_subsidy.memcache

  app:
    # Uncomment this line to use the official edx_enterprise_subsidy base image
    # image: openedx/edx_enterprise_subsidy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edx_enterprise_subsidy.app
    volumes:
      - .:/edx/app/edx-enterprise-subsidy
      - ../src:/edx/src:cached

    command: bash -c 'while true; do python /edx/app/edx-enterprise-subsidy/manage.py runserver 0.0.0.0:18280; sleep 2; done'
    environment:
      DJANGO_SETTINGS_MODULE: edx_enterprise_subsidy.settings.devstack
    ports:
      - "18280:18280" # TODO: change this to your port
    networks:
      - devstack_default
    stdin_open: true
    tty: true

networks:
  devstack_default:
    external: true

volumes:
  edx_enterprise_subsidy_mysql:
